<?php

namespace StudentsSearchBundle\Repository;

/**
 * CommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityRepository extends \Doctrine\ORM\EntityRepository {

    public function findByCountyId($countyId) {
        $query = $this->getEntityManager()->createQuery("
            SELECT community
            FROM StudentsSearchBundle:Community community
            LEFT JOIN community.county_id county
            WHERE county.id = :countyId
        ")->setParameter('countyId', $countyId);
        return $query->getArrayResult();
    }

}
