<?php

namespace StudentsSearchBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository {

    public function findByName($names) {
        $query = $this->getEntityManager()->createQueryBuilder("student")
                ->select("student")
                ->from("StudentsSearchBundle:Student", "student")
                ->where("student.name LIKE :name")
                ->orderby("student.name")
                ->setParameter("name", $names . "%")
                ->getQuery()
                ->getResult();
        return $query;        
    }

    public function findByDistrict($names, $district) {
        $query = $this->getEntityManager()->createQueryBuilder("student")
                ->select("student")
                ->from("StudentsSearchBundle:Student", "student")
                ->where("student.name LIKE :name")
                ->andWhere("student.district = :district")
                ->orderby("student.name")
                ->setParameter("name", $names . "%")
                ->setParameter("district", $district)
                ->getQuery()
                ->getResult();
        return $query;
    }

    public function findByCounty($names, $county) {
        $query = $this->getEntityManager()->createQueryBuilder("student")
                ->select("student")
                ->from("StudentsSearchBundle:Student", "student")
                ->where("student.name LIKE :name")
                ->andWhere("student.county = :county")
                ->orderby("student.name")
                ->setParameter("name", $names . "%")
                ->setParameter("county", $county)
                ->getQuery()
                ->getResult();
        return $query;
    }

    public function findByCommunity($names, $community) {
        $query = $this->getEntityManager()->createQueryBuilder("student")
                ->select("student")
                ->from("StudentsSearchBundle:Student", "student")
                ->where("student.name LIKE :name")
                ->andWhere("student.community = :community")
                ->orderby("student.name")
                ->setParameter("name", $names . "%")
                ->setParameter("community", $community)
                ->getQuery()
                ->getResult();
        return $query;
    }

}
