<?php

namespace StudentsSearchBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository {

    public function findByName($names) {
        $query = $this->getEntityManager()->createQuery("
               SELECT student 
               FROM StudentsSearchBundle:Student student
               WHERE student.name LIKE :name
               ORDER BY student.name
               ")
                ->setParameter('name', $names . "%")
                ->getResult();
        return $query;
    }

    public function findByDistrict($names, $district) {
        $query = $this->getEntityManager()->createQuery("
               SELECT student 
               FROM StudentsSearchBundle:Student student
               WHERE student.name LIKE :name
               AND student.district = :district
               ORDER BY student.name
               ")
                ->setParameters([
                    "name" => $names . "%",
                    "district" => $district
                ])
                ->getResult();
        return $query;
    }

    public function findByDistrictAndCounty($names,  $county) {
        $query = $this->getEntityManager()->createQuery("
               SELECT student 
               FROM StudentsSearchBundle:Student student
               WHERE student.name LIKE :name
               AND student.county = :county
               ORDER BY student.name
               ")
                ->setParameters([
                    "name" => $names . "%",                   
                    "county" => $county
                ])
                ->getResult();
        return $query;
    }

    public function findByDistrictAndCountyAndCommunity($names, $community) {
        $query = $this->getEntityManager()->createQuery("
               SELECT student 
               FROM StudentsSearchBundle:Student student
               WHERE student.name LIKE :name
               AND student.community = :community
               ORDER BY student.name
               ")
                ->setParameters([
                    "name" => $names . "%",
                    "community" => $community
                ])
                ->getResult();
        return $query;
    }

}
